version: '3.9'

services:
  postgres:
    image: postgres:13.22-alpine3.22
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: loanuser
      POSTGRES_PASSWORD: loanpass
      POSTGRES_DB: loandb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: